linters:
  enable-all: true
  disable:
    - gci # conflict with other formatters
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated

issues:
  exclude-rules:
    - path: _test\.go # go test files
      linters:
        - gochecknoglobals # useful for reusing test values
        - exhaustivestruct # decrease verbosity of discord types

  include:
    - EXC0002 # issues about comments from golint
